CREATE TABLE PRODUCT_INVENTORY (
    ID BIGINT PRIMARY KEY,
    PUBLIC_ID UUID NOT NULL,
    QUANTITY REAL,
    UNIT VARCHAR(16),
    PRODUCT_ID BIGINT,
    WAREHOUSE_ID SERIAL
);

CREATE INDEX IDX_PRODUCT_INV_ID ON PRODUCT_INVENTORY (ID);
