CREATE TABLE DELIVERY (
    ID BIGSERIAL PRIMARY KEY,
    PUBLIC_ID UUID NOT NULL,
    COMMAND_TYPE VARCHAR(16) NOT NULL,
    METHOD VARCHAR(16) NOT NULL,
    PRODUCT_PUBLIC_ID UUID,
    QUANTITY REAL,
    PARENT_ID BIGINT,
    STATUS VARCHAR(16)
);

CREATE INDEX IDX_DELIVERY_PUB_ID ON DELIVERY (PUBLIC_ID);
CREATE INDEX IDX_DELIVERY_ID ON DELIVERY (ID);
CREATE INDEX IDX_DELIVERY_STATUS ON DELIVERY (STATUS);
